<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CASHIER</name>
   <tag></tag>
   <elementGuidId>988cba7f-a666-44db-8150-c526bbf038b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#5-CASHIER</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='5-CASHIER']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>73fe247c-502c-4e0c-9769-917ed03dba5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f4be86d-acdc-403d-a4e7-a482a4322c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>5-CASHIER</value>
      <webElementGuid>3367ad17-1a8a-4897-8c44-22c11dcf0c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item list-group-item-action py-4 btn-default btn-cashier</value>
      <webElementGuid>9bfa4cc2-f889-4e59-a32b-f1c88e17feae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> CASHIER </value>
      <webElementGuid>382242bf-7616-429b-82bc-f84f9d06980b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5-CASHIER&quot;)</value>
      <webElementGuid>1d0e9914-1acc-467d-ba18-1965340e5cde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='5-CASHIER']</value>
      <webElementGuid>7cd0b78e-bcfa-45cf-9143-d45f08630ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[6]/div</value>
      <webElementGuid>4a09c3eb-e693-480a-9cd0-37889df67bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UTILITY'])[1]/following::div[2]</value>
      <webElementGuid>394da25f-b746-43e8-bd0a-83787dc5f422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REPORT'])[1]/following::div[4]</value>
      <webElementGuid>f574d505-7f40-4580-b474-fc1dfc1f7faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AWAL HARI'])[1]/preceding::div[1]</value>
      <webElementGuid>2f0feab3-fb83-4d69-8a08-03ee845308c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CASHIER']/parent::*</value>
      <webElementGuid>f609dffb-b51d-49d3-b56f-f5eb3fe82b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>77c7c045-0b78-496b-aba0-529f51fc468a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '5-CASHIER' and (text() = ' CASHIER ' or . = ' CASHIER ')]</value>
      <webElementGuid>8423ecd1-f3ba-47eb-8586-c2f2fdf921df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
