<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OPENING</name>
   <tag></tag>
   <elementGuidId>12a5c988-e91d-4910-8fc2-47e4fbf2b3c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.btn.btn-lg.btn-set.btn-cashier > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div[2]/div/div/div[4]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bd87b335-e5fb-4b14-b34d-1ed965544b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> OPENING </value>
      <webElementGuid>bd142685-2d98-476f-87f8-dd67309ed248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;home position-fixed top-0 end-0 bottom-0 start-0&quot;]/main[@class=&quot;ps-4 row justify-content-center&quot;]/div[@class=&quot;col-10&quot;]/div[@class=&quot;HomeSPV&quot;]/div[@class=&quot;row rows-col-12 gap-4 panel-scroll&quot;]/div[@class=&quot;col d-flex align-items-start&quot;]/div[@class=&quot;btn btn-lg btn-set btn-cashier&quot;]/div[1]</value>
      <webElementGuid>6db09626-f21c-4c20-96ad-531aef6231c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div[2]/div/div/div[4]/div/div</value>
      <webElementGuid>8705da1e-301a-434c-81eb-9be6c14b88a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CASHIER'])[1]/following::div[9]</value>
      <webElementGuid>1d0bae48-b23a-478b-b4b8-8180ed221a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UTILITY'])[1]/following::div[11]</value>
      <webElementGuid>0e4e77d8-9f98-40ab-8ac7-745cb8c9f57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLOSING'])[1]/preceding::div[1]</value>
      <webElementGuid>a26ac0f8-20db-426b-b693-e7c9614f0992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORDER'])[1]/preceding::div[3]</value>
      <webElementGuid>11de64fb-6edb-4373-a85d-8dfc7c22d518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OPENING']/parent::*</value>
      <webElementGuid>4880373f-05ca-42fe-928c-8e336bc8a2db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>eed77df0-f5c0-4a54-b0e7-2ffba864c8d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' OPENING ' or . = ' OPENING ')]</value>
      <webElementGuid>02505e3f-7095-4eee-9cec-02de5e54b5c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
