<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Default PrinterPrinter HO (Gud_45e032</name>
   <tag></tag>
   <elementGuidId>3aa5d92b-62f0-4c24-9eaa-eb2e2f5088ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__20</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='__BVID__20']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dd075121-5cd8-4e6a-ac08-3fd26ac41a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2 custom-select custom-select-lg</value>
      <webElementGuid>1c16aef6-ffd9-45c4-accf-56f30977c2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__20</value>
      <webElementGuid>f90b7bf4-b0e8-4abd-942d-cde72370ffc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Default PrinterPrinter HO (Gudang)HPRT TP809BILL Epson1BILL23Bill 202BILL DIHPRT DEVBILLTESTDP 1BILL CAE PANTURA</value>
      <webElementGuid>8e343e07-946b-4264-9ca8-7cf042792b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__20&quot;)</value>
      <webElementGuid>ce4b9a5f-2b00-4990-a40a-988bbd160ac0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='__BVID__20']</value>
      <webElementGuid>acafd16a-89e4-48fb-89b9-509cee2272e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div[2]/select</value>
      <webElementGuid>a4afe95b-65f1-48a7-9f62-bc9ddf01f134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe User'])[1]/following::select[1]</value>
      <webElementGuid>a6d3b4bb-efba-4a70-a9de-d4093083acbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default Printer'])[1]/following::select[2]</value>
      <webElementGuid>b62d4a2f-5688-4b33-9663-3fd8af764bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Print'])[1]/preceding::select[1]</value>
      <webElementGuid>d8a9d690-f477-462c-8167-d562046df20f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::select[1]</value>
      <webElementGuid>d40572c8-e197-4389-8d67-7e88dffa66a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>5cc2ddd0-ed1f-4168-a47e-847686e4d723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '__BVID__20' and (text() = 'Pilih Default PrinterPrinter HO (Gudang)HPRT TP809BILL Epson1BILL23Bill 202BILL DIHPRT DEVBILLTESTDP 1BILL CAE PANTURA' or . = 'Pilih Default PrinterPrinter HO (Gudang)HPRT TP809BILL Epson1BILL23Bill 202BILL DIHPRT DEVBILLTESTDP 1BILL CAE PANTURA')]</value>
      <webElementGuid>89d6c0f4-9e82-4da3-952f-fd4bc0b6746f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
