<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Tipe User Kasir 1Kasir 2Kasir 3Kasir_c131aa</name>
   <tag></tag>
   <elementGuidId>5f79bb4c-0b24-4d23-aca6-8df1ffeccde1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__19</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='__BVID__19']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4d6f8556-7c0f-473c-b3be-f42ac9f3862e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2 custom-select custom-select-lg</value>
      <webElementGuid>11e36dca-981e-42f6-af1e-2558d75eb0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__19</value>
      <webElementGuid>530681e3-2537-4379-a233-91ccd42743d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tipe User Kasir 1Kasir 2Kasir 3Kasir 4Managerial</value>
      <webElementGuid>11202b81-a876-462f-b830-3dad9e632f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__19&quot;)</value>
      <webElementGuid>cf6efefc-c812-4a22-972e-ae12e5f39b58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='__BVID__19']</value>
      <webElementGuid>7c4517a5-512c-4b98-b2ba-9ce081002768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div/select</value>
      <webElementGuid>5e70db99-eb77-43cc-9942-05837fac217e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default Printer'])[1]/following::select[1]</value>
      <webElementGuid>353c343e-4b4d-4355-b9ca-2edfcb1f4943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOGOUT'])[1]/following::select[1]</value>
      <webElementGuid>b18eb4b4-f590-4a05-9256-ff084c7cbbd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Print'])[1]/preceding::select[2]</value>
      <webElementGuid>4eb42d29-94ea-44de-9038-0f12e2fd8f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>131dd888-24f8-47f9-a039-ede5398a8493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '__BVID__19' and (text() = ' Tipe User Kasir 1Kasir 2Kasir 3Kasir 4Managerial' or . = ' Tipe User Kasir 1Kasir 2Kasir 3Kasir 4Managerial')]</value>
      <webElementGuid>8313dab7-ccb0-4cae-9569-6f09c6c9ad3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
