<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CASHIER</name>
   <tag></tag>
   <elementGuidId>c36f9539-e904-4085-a372-12cdb54205ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#5-CASHIER</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='5-CASHIER']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3613db43-f031-4188-9aee-42aaafe15a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fea51615-0a4d-494d-b87d-5d7ca4b4923e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>5-CASHIER</value>
      <webElementGuid>2bfd4810-1e2c-4bf9-a9fa-22bf5d65a3dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item list-group-item-action py-4 btn-default btn-cashier</value>
      <webElementGuid>81a9fd65-4f15-408d-a0b8-4a6d609b7e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> CASHIER </value>
      <webElementGuid>729456b8-9ac4-4b17-878f-4955c45f89d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5-CASHIER&quot;)</value>
      <webElementGuid>9f755a68-8a08-4c42-b33f-4960cffc7721</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='5-CASHIER']</value>
      <webElementGuid>b77caa3e-2252-4093-b5a9-f5933dff1e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[6]/div</value>
      <webElementGuid>96b23b11-84c5-4a4e-86b4-8adc39a67072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UTILITY'])[1]/following::div[2]</value>
      <webElementGuid>8b7b9cce-0e9e-49bd-9276-bcf98d562122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REPORT'])[1]/following::div[4]</value>
      <webElementGuid>5620e225-a7a0-43c4-a204-39eaf7bd415f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AWAL HARI'])[1]/preceding::div[1]</value>
      <webElementGuid>966961a5-2aa9-4e89-9e68-5b03bc90ecb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CASHIER']/parent::*</value>
      <webElementGuid>71b55977-821d-4f88-a972-946a8d73eb73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>cd0e5571-2f8d-4d75-b349-61188217125f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '5-CASHIER' and (text() = ' CASHIER ' or . = ' CASHIER ')]</value>
      <webElementGuid>8a9ff335-86cd-4fe2-adca-68c71470f279</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
