<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nominal Cash Opening_input_opening</name>
   <tag></tag>
   <elementGuidId>825fc14b-bb6a-4378-be1e-0189a9c2ca58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_opening</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_opening']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31ac6fcb-0cb5-406f-beb5-8af45343ab03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_opening</value>
      <webElementGuid>b21fed38-5e12-4d61-9d63-c73f25826b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>a20bb127-e213-4778-b5e9-e7befb112179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-input mt-1 
                    shadow</value>
      <webElementGuid>bef5e264-ad94-4b37-8c35-b4a05d4cdebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Rp 5.000.000</value>
      <webElementGuid>ddd403a5-ba14-4124-aa24-ad27783c594d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_opening&quot;)</value>
      <webElementGuid>edb7a2a6-51ba-4a3c-ba8c-ee34ae31725e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_opening']</value>
      <webElementGuid>dbc55211-5715-4632-a084-5b81e9398b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swal2-html-container']/div/input</value>
      <webElementGuid>ec800468-0659-4316-bdb5-dca7dddd5b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/input</value>
      <webElementGuid>85b6e6cc-e670-4c0d-94cf-51b3b8c16890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input_opening']</value>
      <webElementGuid>270112c0-122e-4a43-9cfa-d795e2b71a2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
